name: pnpm run build
description: Shared pnpm build step

inputs:
  package_path:
    description: 'Change to directory prior to build'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: 'pnpm run build'
      shell: 'sh -e -o pipefail {0}'
      env:
        package_path: ${{ inputs.package_path }}
      run: |
        # some packages use node-gyp
        apk add --no-cache build-base python3

        corepack enable
        pnpm ci

        if [ -n "${package_path}" ]; then
          cd "${package_path}"
        fi
        # test
        pwd

        pnpm run build

        printf '\nNODE: %s\nPNPM: %s\n\n' "$(node --version)" "$(pnpm --version)"
