minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
engineStrict: true

packages:
  - 'packages/*'

overrides:
  'jest-environment-puppeteer>jest-environment-node': '^30.4.1'
  'ip-address@9': '^10.5.0'
  'glob@10': '^12.0.0'
  'uuid@<11.1.1': '^11.1.1'

allowBuilds:
  esbuild: true
  core-js: true
  unrs-resolver: true
  puppeteer: true

trustPolicyExclude:
  - 'semver@6.3.1'
  - 'undici-types@6.19.8'
