minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
engineStrict: true

packages:
  - 'packages/*'

allowBuilds:
  core-js: true
  esbuild: true
  husky: true
  netlify-cli: true
  puppeteer: true
  sharp: true
  unix-dgram: true
  unrs-resolver: true

overrides:
  hot-shots>unix-dgram: 2.0.7
