minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
engineStrict: true

packages:
  - 'packages/*'

allowBuilds:
  core-js: true
  unrs-resolver: true
  puppeteer: true

trustPolicyExclude:
  - 'semver@6.3.1'
  - 'undici-types@6.19.8'
