name: Check tests

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install the dependencies 🧱
        shell: bash
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: |
          corepack enable
          pnpm ci

      - name: Check Linter and Build 📑
        shell: bash
        run: |
          pnpm run build
          pnpm exec eslint . --ext .js,.jsx,.ts,.tsx

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install the dependencies 🧱
        shell: bash
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: |
          corepack enable
          pnpm ci

      - name: Unit Testing 🧪
        shell: bash
        working-directory: './packages/millicast-sdk'
        run: pnpm run test-unit

  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install the dependencies 🧱
        shell: bash
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: |
          corepack enable
          pnpm ci

      - name: End-to-End Testing
        shell: bash
        working-directory: './packages/millicast-sdk'
        env:
          ACCOUNT_ID: ${{ vars.PUBLISHER_DEMO_ACC_ID }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISHER_DEMO_TOKEN }}
        run: pnpm run test-e2e

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install the dependencies 🧱
        shell: bash
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: |
          corepack enable
          pnpm ci

      - name: build docs
        shell: bash
        run: pnpm run build-docs
