name: Check tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      # This identifies the "base" and "head" commits for Nx
      - name: Derive appropriate SHAs for base and head for affected commands
        uses: nrwl/nx-set-shas@v4

      - name: Setup Node.js & Cache 🧱
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Build and Tests
        run: npx nx affected -t test build build-docs --parallel=3

      - name: Lint SDK Only
        run: npx nx lint @millicast/sdk

  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Derive appropriate SHAs
        uses: nrwl/nx-set-shas@v4
      
      - name: Setup Node.js & Cache 🧱
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run E2E
        run: npx nx affected -t test-e2e
        env:
          ACCOUNT_ID: ${{ vars.PUBLISHER_DEMO_ACC_ID }}
          PUBLISH_TOKEN: ${{ secrets.PUBLISHER_DEMO_TOKEN }}