name: Create CHANGELOG

on:
  push:
    branches:
      - main
      - feature/add-changesets

jobs:
  create-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run changeset version
        run: npx changeset version
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --title "Bump version and update CHANGELOG.md" --body "Changeset version updated the CHANGELOG.md file and version number" --head feature/add-changesets --base main
