name: 'Build dryrun'

on:
  workflow_dispatch:
  push:
    tags:
      - '**'
    branches:
      - '**'

jobs:
  dryrun:
    name: "Build dryrun"
    runs-on: ubuntu-latest
    container: node:24-alpine
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/actions/pnpm-build
        with:
          package_path: './packages/millicast-sdk'
