name: New Test Suite

on:
  pull_request:

jobs:
  new-e2e-tests:
    runs-on: ubuntu-latest
    env:
      E2E_DIR: ./packages/millicast-sdk/e2e-tests
      E2E_TEST_CONFIG: ./packages/millicast-sdk/e2e-tests/test.config.json

      ACCOUNT_ID: ${{secrets.PUBLISHER_ACCOUNT_ID}}
      MILLICAST_STREAM_NAME: ${{vars.PUBLISHER_STREAM_NAME}}
      PUBLISH_TOKEN: ${{secrets.PUBLISHER_TOKEN}}
      MILLICAST_DIRECTOR_ENDPOINT: ${{vars.PUBLISHER_DIRECTOR_EP}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-install
      - name: Suite Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y moreutils
          sudo apt-get --only-upgrade install google-chrome-stable
          npm install playwright
          # npm run prepare
          npm run build
          npm run demo-app:setup
      - name: Execute Test Suite
        run: |
          # Disable artifact collection
          jq '.video = "off"' ${E2E_TEST_CONFIG} | sponge ${E2E_TEST_CONFIG}
          jq '.trace = "off"' ${E2E_TEST_CONFIG} | sponge ${E2E_TEST_CONFIG}
          # jq '.har = "off"' ${E2E_TEST_CONFIG} | sponge ${E2E_TEST_CONFIG}
          jq '.retry = "0"' ${E2E_TEST_CONFIG} | sponge ${E2E_TEST_CONFIG}

          npm run test-websdk -- tags "not @skip and not @ignore"
      - name: Suite Teardown
        if: always()
        run: |
          npm run demo-app:teardown
          npm run test:report
          echo ${MILLICAST_STREAM_NAME} >> ./packages/millicast-sdk/e2e-tests/test-reports/data.txt
          echo ${MILLICAST_DIRECTOR_ENDPOINT} >> ./packages/millicast-sdk/e2e-tests/test-reports/data.txt
          echo ${ACCOUNT_ID} >> ./packages/millicast-sdk/e2e-tests/test-reports/data.txt
          echo ${PUBLISH_TOKEN} >> ./packages/millicast-sdk/e2e-tests/test-reports/data.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-artifacts
          path: ./packages/millicast-sdk/e2e-tests/test-reports/
          retention-days: 2