name: New Test Suite

on:
  pull_request:

jobs:
  new-integration-tests:
    runs-on: ubuntu-latest
    env:
      INTEGRATION_DIR: ./packages/millicast-sdk/integration-tests
      INTEGRATION_TEST_CONFIG: ./packages/millicast-sdk/integration-tests/test.config.json

      MILLICAST_ACCOUNT_ID: ${{secrets.PUBLISHER_ACCOUNT_ID}}
      MILLICAST_STREAM_NAME: ${{vars.PUBLISHER_STREAM_NAME}}
      MILLICAST_PUBLISH_TOKEN: ${{secrets.PUBLISHER_TOKEN}}
      MILLICAST_DIRECTOR_ENDPOINT: ${{vars.PUBLISHER_DIRECTOR_EP}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-install
      - name: Suite Setup
        run: |
          sudo apt-get update
          sudo apt-get install -y moreutils
          sudo apt-get --only-upgrade install google-chrome-stable
          npm install playwright
          npm run build
          npm run demo-app:setup
      - name: Execute Test Suite
        run: |
          # Disable artifact collection
          jq '.video = "off"' ${INTEGRATION_TEST_CONFIG} | sponge ${INTEGRATION_TEST_CONFIG}
          jq '.trace = "off"' ${INTEGRATION_TEST_CONFIG} | sponge ${INTEGRATION_TEST_CONFIG}
          jq '.har = "off"' ${INTEGRATION_TEST_CONFIG} | sponge ${INTEGRATION_TEST_CONFIG}

          npm run test-websdk -- tags "not @skip and not @ignore"
      - name: Suite Teardown
        if: always()
        run: |
          npm run demo-app:teardown
          npm run test:report
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-artifacts
          path: ./packages/millicast-sdk/integration-tests/test-reports/
          retention-days: 2
