name: New Release

on:
  release:
    types: [created]
  push:
    branches:
      - main
    tags:
      - 'next-*'

permissions:
  id-token: write  # Required for OIDC
  contents: write

jobs:
  build-sdk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install the dependencies 🧱
        run: npm ci
      
      - name: Build the SDK 🔧
        run: npm run build
      
      - name: Test the package 🔧
        run: npm run test
        env:
          ACCOUNT_ID: ${{vars.PUBLISHER_DEMO_ACC_ID}}
          PUBLISH_TOKEN: ${{secrets.PUBLISHER_DEMO_TOKEN}}

      - name: Upload SDK build artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdk-dist
          path: packages/millicast-sdk/dist

  publish-npm:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build-sdk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install the dependencies 🧱
        run: npm ci

      - name: Add Readme to package
        run: cp README.md packages/millicast-sdk/README.md

      - name: Download SDK build artifact
        uses: actions/download-artifact@v4
        with: 
          name: sdk-dist
          path: packages/millicast-sdk/dist

      - name: Configure NPMJS 🔧
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Deploy release to NPMJS 🚀
        if: ${{ !contains(github.ref, 'rc') }}
        working-directory: './packages/millicast-sdk'
        run: npm publish --workspaces true --access=public

      - name: Deploy next release to NPMJS 🚀
        if: ${{ startsWith(github.ref, 'refs/tags/next-') }}
        working-directory: './packages/millicast-sdk'
        run: npm publish --workspaces true --access=public --tag next
