name: 'RELEASE: Bump version, create tag/release, and pnpm publish'

on:
  workflow_dispatch:
    inputs:
      bump_version:
        type: choice
        required: true
        description: Which part of version to bump
        options:
          - patch
          - minor
          - major
          - prerelease
      prerelease_id:
        type: string
        required: false
        # only used if bump_version is 'prerelease'
        # otherwise can be ignored
        description: Prerelease identifier
        default: 'alpha'
      skip_publish:
        type: boolean
        required: false
        description: Skip pnpm publish
        default: false

jobs:
  next-version:
    uses: millicast/github-actions/.github/workflows/npm-version-release.yml@v1.0.2
    # should ONLY be used from main
    if: github.ref_name == 'main' || inputs.bump_version == 'prerelease'
    permissions:
      contents: write
    secrets: inherit
    with:
      bump_version: ${{ inputs.bump_version }}
      prerelease_id: ${{ inputs.prerelease_id }}
      skip_tag: ${{ inputs.bump_version == 'prerelease' }}

  build-publish:
    uses: ./.github/workflows/pnpm-build-publish.yml
    needs: [next-version]
    if: success() && inputs.skip_publish != true
    permissions:
      contents: read
      id-token: write
    with:
      ref: ${{ inputs.bump_version != 'prerelease' && format('v{0}', needs.next-version.outputs.semVer) || needs.next-version.outputs.newHeadSha }}
      dist_tag: ${{ inputs.bump_version == 'prerelease' && inputs.prerelease_id || '' }}
