name: pnpm-build-publish

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'git reference to checkout'
        required: true
        type: string
      dist_tag:
        description: 'Distribution tag to publish package with'
        required: false
        type: string
      dryrun:
        description: 'dryrun'
        required: false
        type: boolean
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      dist_tag:
        required: false
        type: string
      dryrun:
        required: false
        type: boolean

jobs:
  build-publish:
    name: "build-publish ${{ inputs.ref }}"
    runs-on: ubuntu-latest
    container: node:24-alpine
    permissions:
      contents: read
      id-token: write
    defaults:
      run:
        shell: 'ash -euo pipefail {0}'
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}

      - name: "pnpm build"
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        run: |
          cp README.md ./packages/millicast-sdk/

          corepack enable
          pnpm ci

          pnpm --filter @millicast/sdk run build
          pnpm --filter @millicast/sdk run build-docs

          printf '\nNODE: %s\nPNPM: %s\n\n' "$(node --version)" "$(pnpm --version)"

      - uses: actions/upload-artifact@v7
        with:
          name: sdk-docs
          path: packages/millicast-sdk/docs
          retention-days: 1

      - name: "pnpm publish"
        env:
          dist_tag: ${{ inputs.dist_tag }}
          dryrun: ${{ inputs.dryrun || 'false' }}
        run: |
          set --
          if [ -n "${dist_tag}" ]; then
            set -- "$@" --tag "${dist_tag}"
          fi
          if [ "${dryrun}" = 'true' ]; then
            set -- "$@" --dry-run
          fi

          pnpm --filter @millicast/sdk publish --provenance --no-git-checks "$@"

  build-docs:
    name: "build-docs ${{ inputs.ref }}"
    runs-on: ubuntu-latest
    container: debian:stable-slim
    if: inputs.dryrun != true
    needs: [build-publish]
    permissions:
      contents: read
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: sdk-docs
          path: packages/millicast-sdk/docs

      - name: Setup GitHub Pages 🛠
        uses: actions/configure-pages@v6

      - name: Upload artifact ⬆️
        uses: actions/upload-pages-artifact@v5
        with:
          path: packages/millicast-sdk/docs

      - id: deployment
        name: Deploy to GitHub Pages 🚀
        uses: actions/deploy-pages@v5
