name: Setup and Install

on:
  workflow_dispatch:

jobs:
  setup-and-install:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js and Cache
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm install